name: 'code_review'
on:
  pull_request:
    types: [opened, synchronize, reopened]
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Infogain-GenAI/AutoReviewer@master
        id: AutoReviewerTest
        with:
          pr_number: ${{ inputs.pr_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_api_instance_name: ${{ secrets.AZURE_OPENAI_API_INSTANCE_NAME }}
          azure_openai_api_deployment_name: ${{ secrets.AZURE_OPENAI_API_DEPLOYMENT_NAME }}
          azure_openai_api_version: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          model_name: ${{ secrets.MODEL_NAME }}
          exclude_files: '*.json, *.md, *.yml, *.razor'
